// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCat8_jbY6uplEzWo3Fwy2xjZJCo9QMbXs',
    appId: '1:1080552980554:web:d5798212f342155f49a6b3',
    messagingSenderId: '1080552980554',
    projectId: 'checklist-app-z2062',
    authDomain: 'checklist-app-z2062.firebaseapp.com',
    storageBucket: 'checklist-app-z2062.appspot.com',
    measurementId: 'G-8W21QCS8C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9qHjdaAiqhfzr6DvaQFZ9UmJM272QAw',
    appId: '1:1080552980554:android:878e4ba67d05252c49a6b3',
    messagingSenderId: '1080552980554',
    projectId: 'checklist-app-z2062',
    storageBucket: 'checklist-app-z2062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq-OIbNhq9ffCYHsCa4BpMQ1-I0dh54bc',
    appId: '1:1080552980554:ios:d483a8915c1154b349a6b3',
    messagingSenderId: '1080552980554',
    projectId: 'checklist-app-z2062',
    storageBucket: 'checklist-app-z2062.appspot.com',
    iosBundleId: 'com.example.checklistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq-OIbNhq9ffCYHsCa4BpMQ1-I0dh54bc',
    appId: '1:1080552980554:ios:d483a8915c1154b349a6b3',
    messagingSenderId: '1080552980554',
    projectId: 'checklist-app-z2062',
    storageBucket: 'checklist-app-z2062.appspot.com',
    iosBundleId: 'com.example.checklistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCat8_jbY6uplEzWo3Fwy2xjZJCo9QMbXs',
    appId: '1:1080552980554:web:2269621a807d142349a6b3',
    messagingSenderId: '1080552980554',
    projectId: 'checklist-app-z2062',
    authDomain: 'checklist-app-z2062.firebaseapp.com',
    storageBucket: 'checklist-app-z2062.appspot.com',
    measurementId: 'G-ETTTJT1SGC',
  );
}
